# Generated by Django 3.2.9 on 2021-12-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20211222_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organization',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
    ]
